# Generated by Django 5.2.2 on 2025-06-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='total_slots',
            field=models.IntegerField(default=10),
        ),
    ]
